[build]
command =  "rm -rf node_modules package-lock.json && npm install --include=dev && npm run build"

[build.environment]
NODE_VERSION = "22.14.0"
NPM_VERSION = "11.3.0"

[site]
bucket = "./dist"
